spring.application.name=api

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/yoruk}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:}
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.repositories.enabled=false

spring.jackson.modules[0]=com.fasterxml.jackson.databind.Module

spring.main.lazy-initialization=true

server.tomcat.threads.max=10

spring.jpa.open-in-view=false

server.tomcat.accept-count=10

logging.level.org.springframework=DEBUG
logging.level.io.lettuce=DEBUG