spring.application.name=api

server.address=0.0.0.0
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.url=${REDIS_URL}
spring.data.redis.repositories.enabled=false
spring.data.redis.ssl.enabled=true

spring.jackson.modules[0]=com.fasterxml.jackson.databind.Module

logging.level.root=INFO