spring.application.name=api

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/yoruk}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.repositories.enabled=false

spring.jackson.modules[0]=com.fasterxml.jackson.databind.Module